version: "3"
services:
    php-fmp:
        container_name: php-fpm
        build: 
            context: .
            dockerfile: docker/php.Dockerfile
        volumes: 
            - ./:/var/www/kinopub.local
            - ./logs/kinopub.local:/var/www/kinopub.local/log
        links: 
            - postgres

    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: docker/nginx.Dockerfile
        ports: 
            - "8084:80"
        volumes: 
            - ./:/var/www/kinopub.local
            - ./logs/nginx/:/var/log/nginx
        links: 
            - php-fmp
    
    postgres:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_DB: db_kinopub
            POSTGRES_USER: db_user
            POSTGRES_PASSWORD: db_pass
        volumes:
            - ./data/postgresql:/var/lib/postgresql/data
        ports:
            - 5432:5432   
